// Generated by Compyle
// Compyle version: 0.4.0
// Python version: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
// Original filename: test.py
int main()
{
    int a = 2;
    int b = 3;
    int c = 3 + 2;
    return None;
}
