// Generated by Compyle
// Compyle version: 0.4.0
// Python version: 3.8.10 (default, May 26 2023, 14:05:08) [GCC 9.4.0]
// Original filename: test.py

int main()
{
    int a = 2;
    int b = 3;
    int c = a + b;
    return None;
}
